apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alb
  namespace: wanderlust
  annotations:
    # Tells AWS to create a public ALB
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Tells ALB to route directly to Pod IPs (Requires ClusterIP services)
    alb.ingress.kubernetes.io/target-type: ip
    # Optional: Automatically listens on port 80 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      # ALB will pass exactly "/api/posts" to the backend, which perfectly matches your server.js!
      - pathType: Prefix
        path: /api
        backend:               
          service:
            name: backend-svc
            port:
              number: 8080

      # ALB will pass "/" and everything else to the React frontend        
      - pathType: Prefix
        path: /
        backend:               
          service:
            name: frontend-svc
            port:
              number: 5173