apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: wanderlust
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  
