name: image build and push to ecr

on:
  push:
    branches: 
      - cicd

permissions:
  contents: read
  id-token: write      

jobs:
    build-and-push:
      runs-on: ubuntu-latest

      steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: DEBUG - Print Exact GitHub Context
        run: |
          echo "The exact repository string AWS expects is: repo:${{ github.repository }}:*"      

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945714973951:role/GitHub-Actions-OIDC-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify Identity 
        run: |
          aws sts get-caller-identity       

      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push backend image
        env: 
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          IMG_TAG: ${{ github.sha }}
          REPOSITORY: wanderlust-backend
        run:  |
          echo "backend image to ECR..."
          cd backend
          docker build -t $ECR_URL/$REPOSITORY:$IMG_TAG .
          docker push $ECR_URL/$REPOSITORY:$IMG_TAG    

      - name: build and push frontend image
        env: 
          ECR_URL: ${{ steps.login-ecr.outputs.registry }}
          IMG_TAG: ${{ github.sha }}
          REPOSITORY: wanderlust-frontend
        run:  |
          echo "frontend image to ECR..."
          cd frontend
          docker build -t $ECR_URL/$REPOSITORY:$IMG_TAG .
          docker push $ECR_URL/$REPOSITORY:$IMG_TAG